"""add_image_views

Revision ID: 1df9ce606352
Revises: 0002_category_orders
Create Date: 2026-06-16 07:00:22.184193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df9ce606352'
down_revision: Union[str, Sequence[str], None] = '0002_category_orders'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('front_view', sa.String(length=512), nullable=True))
    op.add_column('products', sa.Column('side_view', sa.String(length=512), nullable=True))
    op.add_column('products', sa.Column('lifestyle_images', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('thumbnail', sa.String(length=512), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'thumbnail')
    op.drop_column('products', 'lifestyle_images')
    op.drop_column('products', 'side_view')
    op.drop_column('products', 'front_view')
    # ### end Alembic commands ###
